import {
  Car,
  Clock,
  Wifi,
  Gauge,
  Dumbbell,
  UsersRound,
  PersonStanding,
  ShowerHead,
  CircleCheck,
  Utensils,
  HeartPulse,
  ShoppingBag,
  ClipboardList,
  CalendarCheck,
  QrCode,
  Sun,
} from 'lucide-react';

// Icon and category definitions
export const ICON_MAPPING = {
  'Cardio Equipment': Gauge,
  'Strength Machines': Dumbbell,
  'Group Classes': UsersRound,
  'CrossFit Area': Dumbbell,
  'Gymnastic Rings': PersonStanding,
  'Showers & Changing Rooms': ShowerHead,
  'Personal Lockers': CircleCheck,
  'Towels & Toiletries': ShowerHead,
  Parking: Car,
  'Free Wi-Fi': Wifi,
  'Food Buffet': Utensils,
  'Massage & Physiotherapy': HeartPulse,
  'Sportswear & Gear Shop': ShoppingBag,
  'Personal Trainer': ClipboardList,
  'Custom Workout Plans': ClipboardList,
  'Body Composition Analysis': ClipboardList,
  'Nutrition & Wellness Coaching': ClipboardList,
  'Online Class Access': Wifi,
  'Male/Female Trainer Option': UsersRound,
  'Online Booking': CalendarCheck,
  'QR Code Entry': QrCode,
  'Open 8am - 10pm': Clock,
  'Peak Hour 3-5pm': Sun,
};

export const FACILITIES_CATEGORIES = {
  'Main Fitness Facilities': [
    'Cardio Equipment',
    'Strength Machines',
    'Free Weights',
    'Group Classes',
    'CrossFit Area',
    'Swimming Pool',
    'Gymnastic Rings',
  ],
  'Comfort & Amenities': [
    'Showers & Changing Rooms',
    'Personal Lockers',
    'Towels & Toiletries',
    'Parking',
    'Free Wi-Fi',
    'Food Buffet',
    'Massage & Physiotherapy',
    'Sportswear & Gear Shop',
  ],
  'Coaching & Support': [
    'Personal Trainer',
    'Custom Workout Plans',
    'Body Composition Analysis',
    'Nutrition & Wellness Coaching',
    'Online Class Access',
    'Male/Female Trainer Option',
  ],
  'Time & Booking Features': [
    'Online Booking',
    'QR Code Entry',
    'Open 8am - 10pm',
    'Peak Hour 3-5pm',
  ],
};
